spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/mywms?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username:  root
    password:  123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix:  classpath:/templates/
    suffix: .html
    mode:  LEGACYHTML5
    encoding: UTF-8
    cache: false


server:
  port: 9999

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

# 打印sql
logging:
  level:
    com:
      lfm:
        wms:
          dao : debug

